### ISSUE TITLE
tofu segfaults in a log at startup

### ISSUE THREAD

**Issue by lminiero** [tofuengine/tofu#6]
I'm getting a crash anytime I start the `tofu` executable, both on its own and in the context of a demo. The gdb backtrace is the following:

```
(gdb) bt
#0  0x00007ffff7ce8ffd in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007ffff7bf2858 in __vfprintf_internal () from /lib64/libc.so.6
#2  0x00007ffff7bf2f05 in buffered_vfprintf () from /lib64/libc.so.6
#3  0x000000000047cf4f in _write (level=LOG_LEVELS_DEBUG, 
    context=0x59c60d "storage", 
    text=0x59c720 "storage cache %p for context %p created for path `%s`", 
    args=0x7fffffff62b8) at src/libs/log.c:87
#4  0x000000000047d0b3 in Log_write (level=LOG_LEVELS_DEBUG, 
    context=0x59c60d "storage", 
    text=0x59c720 "storage cache %p for context %p created for path `%s`")
    at src/libs/log.c:116
#5  0x00000000004d054e in Storage_create (configuration=0x7fffffffd4c0)
    at src/systems/storage.c:95
#6  0x0000000000407aff in Engine_create (options=0x7fffffffd560)
    at src/core/engine.c:133
#7  0x000000000040647d in main (argc=1, argv=0x7fffffffd698) at src/main.c:88
```

Looks like the problem is here:

```
#5  0x00000000004d054e in Storage_create (configuration=0x7fffffffd4c0)
    at src/systems/storage.c:95
95	    LOG_D(LOG_CONTEXT, "storage cache %p for context %p created for path `%s`", storage->cache, storage->context);
```

as there's three printf format specifiers, but only two argument (missing path). Adding `path` as an argument fixes the segfault for me.

**Comment by MarcoLizza** [comment]
Oh! Nice catch!

That's definitely a huge oversight from me! :D Truth is that on my Linux system (which is typically Ubuntu) I don't get a SEGFAULT at all (either in DEBUG or RELEASE version)! The log output (which is plain garbage on that line) totally goes unnoticed in the burst of log information... I totally missed it!

Thanks, I'm closing by fixing this!
